version: '2.1'

services:
  eureka-server:
    build: eureka-server
    mem_limit: 512m
    ports:
      - "8761:8761"
    networks:
      - 'prodshcsales-network'
  api-gateway:
    build: api-gateway
    mem_limit: 512m
    ports:
      - "443:443"
    networks:
      - 'prodshcsales-network'
  products-service:
    build: products-service
    mem_limit: 512m
    ports:
      - "8082:8082"
    networks:
      - 'prodshcsales-network'
  shoppingcarts-service:
    build: shoppingcarts-service
    mem_limit: 512m
    ports:
      - "8083:8083"
    networks:
      - 'prodshcsales-network'
  sales-service:
    build: sales-service
    mem_limit: 512m
    ports:
      - "8084:8084"
    networks:
      - 'prodshcsales-network'

networks:
  prodshcsales-network: