server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: sales-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/sales_service?serverTimezone=UTC
    username: root
    password: 123456789